In [1]:
import numpy as np

In [6]:
arr = np.arange(11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[-1]

10

In [10]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [12]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[0:3]=100

In [15]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [16]:
arr=np.arange(11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:]=99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy[0:6]=[0,1,2,3,4,5]

In [26]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_2d=np.array([[5,10,15], [20,25,30], [35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[1]

array([20, 25, 30])

In [33]:
arr_2d[1][0]

20

In [34]:
arr_2d[1,0]

20

In [38]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d[2]

array([35, 40, 45])

In [40]:
arr_2d[2,:]

array([35, 40, 45])

In [42]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[:,1]

array([10, 25, 40])

In [45]:
arr_2d[:,1:2]

array([[10],
       [25],
       [40]])

In [46]:
arr_2d[1,1] = 55

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [48]:
arr_2d[0,0] = 3.3

In [49]:
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [52]:
v=np.arange(0,30,3)

In [53]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
v[1]

3

In [55]:
idx_list = [1,3,5]

In [56]:
v[idx_list]

array([ 3,  9, 15])

In [57]:
v[[1,3,5]]

array([ 3,  9, 15])

In [58]:
arr2d = np.zeros((10,10),dtype=int)

In [59]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [60]:
arr2d.shape

(10, 10)

In [61]:
arr_len=arr2d.shape[1]

In [62]:
arr_len

10

In [63]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
for i in range(arr_len):
    arr2d[i] = i

In [66]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [67]:
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [68]:
jj = np.arange(1,17).reshape(4,4)

In [69]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [71]:
jj[1,[1,3]]

array([6, 8])

In [72]:
jj[[0,3], 1]

array([ 2, 14])

In [73]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [75]:
jj[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [77]:
jj[:,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [79]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [80]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [81]:
arr=np.arange(1,11)

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
bool_arr=arr>4

In [86]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [90]:
arr[(arr!=3) & (arr !=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [91]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [93]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [94]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
arr/arr

<ipython-input-95-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
1/arr

<ipython-input-96-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [99]:
arr*5/10-1

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5])

In [100]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.log10(10000)

4.0

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [104]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [105]:
np.sin(np.pi/2)

1.0

In [106]:
np.tan(np.pi/4)

0.9999999999999999