In [1]:
import numpy as np
import pandas as pd

In [2]:
datam = [1,2,39,67,90]

In [3]:
datam

[1, 2, 39, 67, 90]

In [4]:
pd.DataFrame(datam, columns=["column_name"])

column_name
0            1
1            2
2           39
3           67
4           90

In [5]:
m = np.arange(1,10).reshape(3,3)

In [6]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(m, columns=["var1","var2","var2"])

var1  var2  var2
0     1     2     3
1     4     5     6
2     7     8     9

In [8]:
df = pd.DataFrame(m, columns=["var1","var2","var2"])

In [9]:
df

var1  var2  var2
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df.head(2)

var1  var2  var2
0     1     2     3
1     4     5     6

In [11]:
df.tail(1)

var1  var2  var2
2     7     8     9

In [12]:
df.columns

Index(['var1', 'var2', 'var2'], dtype='object')

In [13]:
for i in df.columns:
    print(i)

var1
var2
var2


In [14]:
df.columns = ["new1","new2","new3"]

In [15]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.shape

(3, 3)

In [18]:
df.ndim

2

In [19]:
df.size

9

In [20]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
type(df.values)

numpy.ndarray

In [22]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [23]:
s1

array([8, 8, 0, 8, 7])

In [24]:
s2

array([3, 9, 8, 5, 5])

In [25]:
s3

array([9, 8, 5, 5, 9])

In [26]:
myDict = {"var1":s1, "var2":s2, "var3":s3}

In [27]:
myDict

{'var1': array([8, 8, 0, 8, 7]),
 'var2': array([3, 9, 8, 5, 5]),
 'var3': array([9, 8, 5, 5, 9])}

In [28]:
df1 = pd.DataFrame(myDict)

In [29]:
df1

var1  var2  var3
0     8     3     9
1     8     9     8
2     0     8     5
3     8     5     5
4     7     5     9

In [30]:
pwd

'C:\\Users\\acer\\DS\\General_workspace'

In [31]:
df3 = pd.read_csv("ornekcsv.csv", delimiter = ";")

In [32]:
df3.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [33]:
df1

var1  var2  var3
0     8     3     9
1     8     9     8
2     0     8     5
3     8     5     5
4     7     5     9

In [34]:
df1[1:3]

var1  var2  var3
1     8     9     8
2     0     8     5

In [35]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [36]:
[i for i in df1.index]

[0, 1, 2, 3, 4]

In [37]:
df1.index = ["a","b","c","d","e"]

In [38]:
df1

var1  var2  var3
a     8     3     9
b     8     9     8
c     0     8     5
d     8     5     5
e     7     5     9

In [39]:
df1["b":"d"]

var1  var2  var3
b     8     9     8
c     0     8     5
d     8     5     5

In [40]:
"var2" in df1

True

In [41]:
"var5" in df1

False

In [42]:
df1["var1"][1:3]

b    8
c    0
Name: var1, dtype: int32

In [43]:
from numpy.random import randn
np.random.seed(101)

In [44]:
df3 = pd.DataFrame(randn(5,4), index = "A B C D E".split(), columns = "W X Y Z".split())

In [45]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
pd.DataFrame(randn(5,4), "A B C D E".split(), "W X Y Z".split())

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [47]:
df3["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [48]:
type(df3["W"])

pandas.core.series.Series

In [49]:
df3[["W"]]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [50]:
type(df3[["W"]])

pandas.core.frame.DataFrame

In [51]:
df3[["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [52]:
df3["W"]["B":"D"]

B    0.651118
C   -2.018168
D    0.188695
Name: W, dtype: float64

In [53]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [54]:
df3["A":"C"]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [55]:
df3["C":"C"]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [56]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df3["new"] = df3["W"] + df3["Y"]

In [58]:
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [59]:
df3["new2"] = df3["W"] * df3["Y"]

In [60]:
df3

W         X         Y         Z       new      new2
A  2.706850  0.628133  0.907969  0.503826  3.614819  2.457737
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959 -0.552198
C -2.018168  0.740122  0.528813 -0.589001 -1.489355 -1.067235
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542 -0.176097
E  0.190794  1.978757  2.605967  0.683509  2.796762  0.497204

In [61]:
df3.drop(["new", "new2"], axis=1, inplace = True)

In [62]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [63]:
df3.drop(["E"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [64]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0    23     6    23
1    10    14     3
2    19    27    16
3    29    12    28
4    11    18     4
5    29     4    20
6    21    16    15
7    27     6    26
8    29     6    25
9    20     7    25

In [66]:
df4.loc[1]

var1    10
var2    14
var3     3
Name: 1, dtype: int32

In [67]:
df4.loc[[1]]

var1  var2  var3
1    10    14     3

In [68]:
df4.loc[1:4]

var1  var2  var3
1    10    14     3
2    19    27    16
3    29    12    28
4    11    18     4

In [69]:
df4.iloc[1:4]

var1  var2  var3
1    10    14     3
2    19    27    16
3    29    12    28

In [70]:
df4.index = "a b c d e f g h i j".split()

In [71]:
df4

var1  var2  var3
a    23     6    23
b    10    14     3
c    19    27    16
d    29    12    28
e    11    18     4
f    29     4    20
g    21    16    15
h    27     6    26
i    29     6    25
j    20     7    25

In [72]:
df4.iloc[1:4] # aynı kod loc ile hata verir

var1  var2  var3
b    10    14     3
c    19    27    16
d    29    12    28

In [73]:
df4.loc["b":"d"]

var1  var2  var3
b    10    14     3
c    19    27    16
d    29    12    28

In [74]:
df4.iloc[1,1]

14

In [75]:
df4.loc["b":"e", "var2"]

b    14
c    27
d    12
e    18
Name: var2, dtype: int32

In [76]:
df4.loc["b":"e"]["var2"]

b    14
c    27
d    12
e    18
Name: var2, dtype: int32

In [77]:
df4.loc["b":"e"][["var2"]]

var2
b    14
c    27
d    12
e    18

In [78]:
df4.loc["b":"e", ["var2"]]

var2
b    14
c    27
d    12
e    18

In [79]:
df4.iloc[1:5,1]

b    14
c    27
d    12
e    18
Name: var2, dtype: int32

In [80]:
df4.iloc[1:5,[1]]

var2
b    14
c    27
d    12
e    18

In [81]:
df4.iloc[1:5]["var2"]

b    14
c    27
d    12
e    18
Name: var2, dtype: int32

In [82]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [83]:
df3.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [84]:
df3.loc[["A"]]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [85]:
df3.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [86]:
df3.iloc[[2]]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [87]:
df3.iloc[:,2]

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [88]:
df3.iloc[:,[2]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [89]:
df3["Y"]

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [90]:
df3.Y

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [91]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [92]:
df3.loc["B","Y"]

-0.8480769834036315

In [93]:
df3.loc[["B"],["Y"]]

Y
B -0.848077

In [94]:
df3.loc[["A", "B"],["W", "Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [95]:
df3.iloc[[0, 1],[0, 2]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [96]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [97]:
df3 > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [98]:
df3[df3 > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [99]:
df3["W"] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [100]:
df3[df3["W"] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [101]:
df3[[True,True,False,False,True]]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
E  0.190794  1.978757  2.605967  0.683509

In [102]:
df3[df3["W"] > 0]["Y"]

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [103]:
df3[df3["W"] > 0][["Y"]]

Y
A  0.907969
B -0.848077
D -0.933237
E  2.605967

In [104]:
df3[df3["W"] > 0][["Y","X"]]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [105]:
df3[(df3["W"] > 0) & (df3["Y"] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [106]:
df3.loc[(df3["X"] > 0), ["X", "Z"]]

X         Z
A  0.628133  0.503826
C  0.740122 -0.589001
E  1.978757  0.683509

In [107]:
df3.loc[((df3["W"] > 2) | (df3["W"] < -2)), ["W", "Y"]]

W         Y
A  2.706850  0.907969
C -2.018168  0.528813

In [108]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [117]:
df3.reset_index(inplace = True)

In [119]:
df3

States         W         X         Y         Z
0     CA  2.706850  0.628133  0.907969  0.503826
1     NY  0.651118 -0.319318 -0.848077  0.605965
2     WY -2.018168  0.740122  0.528813 -0.589001
3     OR  0.188695 -0.758872 -0.933237  0.955057
4     CO  0.190794  1.978757  2.605967  0.683509

In [120]:
df3.reset_index(drop=True)

States         W         X         Y         Z
0     CA  2.706850  0.628133  0.907969  0.503826
1     NY  0.651118 -0.319318 -0.848077  0.605965
2     WY -2.018168  0.740122  0.528813 -0.589001
3     OR  0.188695 -0.758872 -0.933237  0.955057
4     CO  0.190794  1.978757  2.605967  0.683509

In [121]:
newindx = "CA NY WY OR CO".split()

In [122]:
newindx

['CA', 'NY', 'WY', 'OR', 'CO']

In [123]:
df3["States"] = newindx

In [124]:
df3

States         W         X         Y         Z
0     CA  2.706850  0.628133  0.907969  0.503826
1     NY  0.651118 -0.319318 -0.848077  0.605965
2     WY -2.018168  0.740122  0.528813 -0.589001
3     OR  0.188695 -0.758872 -0.933237  0.955057
4     CO  0.190794  1.978757  2.605967  0.683509

In [125]:
df3.set_index("States", inplace = True)

In [126]:
df3

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [127]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2']
inside = [1, 2, 3, 1, 2, 3]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1), ('M1', 2), ('M1', 3), ('M2', 1), ('M2', 2), ('M2', 3)]

In [131]:
hier_index = pd.MultiIndex.from_tuples(multi_index)

In [132]:
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3)],
           )

In [133]:
df5 = pd.DataFrame(np.random.randn(6, 2), index = hier_index, columns = ["A", "B"])

In [134]:
df5

A         B
M1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
M2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

In [135]:
df5.loc["M1"]

A         B
1  0.147027 -0.479448
2  0.558769  1.024810
3 -0.925874  1.862864

In [138]:
df5.loc["M1"].loc[1]

A    0.147027
B   -0.479448
Name: 1, dtype: float64

In [139]:
df5.loc["M1"].loc[[1]]

A         B
1  0.147027 -0.479448

In [140]:
df5.index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3)],
           )

In [142]:
df5.index.names

FrozenList([None, None])

In [143]:
df5.index.names = ["Group", "Num"]

In [144]:
df5

A         B
Group Num                    
M1    1    0.147027 -0.479448
      2    0.558769  1.024810
      3   -0.925874  1.862864
M2    1   -1.133817  0.610478
      2    0.386030  2.084019
      3   -0.376519  0.230336

In [146]:
d = {'num_legs': [4, 4, 2, 2],
     'num_wings': [0, 0, 2, 2],
     'class': ['mammal', 'mammal', 'mammal', 'bird'],
     'animal': ['cat', 'dog', 'bat', 'penguin'],
     'locomotion': ['walks', 'walks', 'flies', 'walks']}
df = pd.DataFrame(data=d)
df = df.set_index(['class', 'animal', 'locomotion'])
df

num_legs  num_wings
class  animal  locomotion                     
mammal cat     walks              4          0
       dog     walks              4          0
       bat     flies              2          2
bird   penguin walks              2          2

In [147]:
df.xs("mammal")

num_legs  num_wings
animal locomotion                     
cat    walks              4          0
dog    walks              4          0
bat    flies              2          2

In [149]:
df.xs(("mammal", "cat"))

num_legs  num_wings
locomotion                     
walks              4          0

In [150]:
df.xs(("mammal", "cat"), level = [0,1])

num_legs  num_wings
locomotion                     
walks              4          0

In [156]:
df.xs(("cat", "walks"), level = [1,2])

num_legs  num_wings
class                      
mammal         4          0

In [153]:
df

num_legs  num_wings
class  animal  locomotion                     
mammal cat     walks              4          0
       dog     walks              4          0
       bat     flies              2          2
bird   penguin walks              2          2

In [162]:
df.xs("cat", level = 1)

num_legs  num_wings
class  locomotion                     
mammal walks              4          0

In [165]:
df.xs(("mammal","cat", "walks"))

num_legs     4
num_wings    0
Name: (mammal, cat, walks), dtype: int64

In [167]:
df.xs(("bird", "walks"), level = [0,"locomotion"])

num_legs  num_wings
animal                      
penguin         2          2

In [168]:
df5

A         B
Group Num                    
M1    1    0.147027 -0.479448
      2    0.558769  1.024810
      3   -0.925874  1.862864
M2    1   -1.133817  0.610478
      2    0.386030  2.084019
      3   -0.376519  0.230336

In [169]:
df5.xs("M1")

A         B
Num                    
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [171]:
df5.xs(("M1",1))

A    0.147027
B   -0.479448
Name: (M1, 1), dtype: float64

In [173]:
df5.xs(("M1",1), level = (0,1))

A         B
Group Num                    
M1    1    0.147027 -0.479448

In [174]:
df5.xs(1, level = 1)

A         B
Group                    
M1     0.147027 -0.479448
M2    -1.133817  0.610478