In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [3]:
np.array([10,88,3,4,5])

array([10, 88,  3,  4,  5])

In [4]:
ser = pd.Series([10,88,3,4,5])

In [5]:
ser

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [6]:
type(ser)

pandas.core.series.Series

In [8]:
ser.dtype

dtype('int64')

In [9]:
ser.size

5

In [10]:
ser.ndim

1

In [11]:
ser.values

array([10, 88,  3,  4,  5], dtype=int64)

In [18]:
[i for i in ser.values]

[10, 88, 3, 4, 5]

In [12]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
ser.head(3)

0    10
1    88
2     3
dtype: int64

In [20]:
ser.tail(3)

2    3
3    4
4    5
dtype: int64

In [21]:
str = "clarusway"
pd.Series([i for i in str])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [28]:
labels = ["a","b","c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {"a":10, "b":20, "c":30}

In [29]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [30]:
pd.Series(data=my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [31]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

In [32]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [33]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [35]:
d

{'a': 10, 'b': 20, 'c': 30}

In [34]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [36]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [37]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [38]:
mix_data = [1, "cat", True]

In [39]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

In [40]:
s = pd.Series(["p","q","r","s"], index = [3,2,4,1])

In [41]:
s

3    p
2    q
4    r
1    s
dtype: object

In [42]:
s.sort_index()

1    s
2    q
3    p
4    r
dtype: object

In [43]:
s

3    p
2    q
4    r
1    s
dtype: object

In [46]:
s.sort_index(ascending = False, inplace=True)

In [47]:
s

4    r
3    p
2    q
1    s
dtype: object

In [48]:
s.sort_values()

3    p
2    q
4    r
1    s
dtype: object

In [49]:
s = pd.Series(["p","q","r","s"], index = [3,2,4,np.nan])

In [50]:
s.sort_index()

2.0    q
3.0    p
4.0    r
NaN    s
dtype: object

In [53]:
s.sort_index(na_position="first")

NaN    s
2.0    q
3.0    p
4.0    r
dtype: object

In [54]:
s = pd.Series(["dog", "cat", "lion", "monkey", "dog"])

In [55]:
s

0       dog
1       cat
2      lion
3    monkey
4       dog
dtype: object

In [57]:
s.isin(["cat", "dog"])

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [58]:
ser1 = pd.Series([1,2,3,4], index = ["USA","Germany", "USSR", "Japan"])

In [59]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [60]:
ser2 = pd.Series([1,2,5,4], index = ["USA","Germany", "Italy", "Japan"])

In [61]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [62]:
ser1["USA"]

1

In [77]:
ser2["USA":"Italy"] #sayıların aksine start:stop dahil olarak slicing yaptı.

USA        1
Germany    2
Italy      5
dtype: int64

In [78]:
ser3 = pd.Series(data = labels)

In [79]:
ser3

0    a
1    b
2    c
dtype: object

In [80]:
ser3[0]

'a'

In [81]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [82]:
a = np.array([1,2,33,444,75])

In [83]:
a

array([  1,   2,  33, 444,  75])

In [84]:
pser = pd.Series(a)

In [85]:
pser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [86]:
pser[0]

1

In [87]:
pser[0:3]

0     1
1     2
2    33
dtype: int32

In [88]:
pser = pd.Series([121,200,150,99], index=["ali","veli","gul","nur"])

In [89]:
pser

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [90]:
pser["ali"]

121

In [91]:
pser[0]

121

In [92]:
pser[["veli","nur"]]

veli    200
nur      99
dtype: int64

In [93]:
pser[0:3]

ali     121
veli    200
gul     150
dtype: int64

In [94]:
pser["ali":"nur"]

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [95]:
pser.index

Index(['ali', 'veli', 'gul', 'nur'], dtype='object')

In [96]:
pser.values

array([121, 200, 150,  99], dtype=int64)

In [104]:
pser.items

<bound method Series.items of ali     121
veli    200
gul     150
nur      99
dtype: int64>

In [105]:
pser.items()

In [117]:
list(pser.items())

TypeError: 'list' object is not callable

In [101]:
for index, value in pser.items():
    print(index, "-", value)

ali - 121
veli - 200
gul - 150
nur - 99


In [107]:
"mehmet" in pser

False

In [108]:
"gul" in pser

True

In [110]:
99 in pser.values

True

In [111]:
pser["veli"] = 571

In [112]:
pser

ali     121
veli    571
gul     150
nur      99
dtype: int64

In [113]:
pser > 130

ali     False
veli     True
gul      True
nur     False
dtype: bool

In [114]:
pser[pser>130]

veli    571
gul     150
dtype: int64