In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [3]:
my_list =[1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6,], [7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0,11,2) # same as the range built in func

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.66384256, 0.06713708, 0.72819369, 0.47216605, 0.92819103])

In [30]:
np.random.rand(5,5)

array([[0.04605346, 0.6490545 , 0.28921123, 0.92594078, 0.4266708 ],
       [0.6183129 , 0.94425847, 0.42396206, 0.97364566, 0.38558912],
       [0.40962363, 0.11137192, 0.27125938, 0.6295282 , 0.34639503],
       [0.67860341, 0.16268817, 0.24972036, 0.94062274, 0.45773898],
       [0.16714795, 0.06797906, 0.36212548, 0.46645273, 0.05044956]])

In [31]:
np.random.randn(4,4)

array([[-0.76985245,  0.58033385, -0.68813257,  0.46989128],
       [ 0.97154343, -0.59997728,  0.83995102, -1.02491731],
       [ 0.42639931,  1.66254078, -0.33812814,  1.02896874],
       [ 0.14429166,  1.15217874,  0.07503734,  0.95191157]])

In [16]:
np.random.randint(1,100,10)

array([72, 74, 31, 79, 66, 33, 63, 18, 10,  2])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
ranarr

array([20,  0, 18, 39, 41, 11, 38,  0,  2, 30])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

41

In [42]:
ranarr.min()

0

In [43]:
ranarr

array([20,  0, 18, 39, 41, 11, 38,  0,  2, 30])

In [44]:
ranarr.argmax()

4

In [45]:
ranarr.argmin()

1

In [46]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr.shape

(5, 5)

In [51]:
arr.dtype

dtype('int32')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

7